// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ydfzjpzwbgyrtjxslsbs.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InlkZnpqcHp3Ymd5cnRqeHNsc2JzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ0NTIwNjAsImV4cCI6MjA2MDAyODA2MH0.Fu61Vjq_ZbNGCr950A9rk_C0AaS8zG_IQ04r2NWUzpM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);